var database = [
  {
    "title": "Modals",
    "localUrl": "Modal.html",
    "fullUrl": "",
    "description": "Modal test",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Modals"
  },
  {
    "title": "Preview",
    "localUrl": "Preview.html",
    "fullUrl": "",
    "description": "The official preview page of MediascriptWiki",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Pages"
  },
  {
    "title": "Dog",
    "localUrl": "dog.html",
    "fullUrl": "",
    "description": "A domestic animal known as a dog.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals, people"
  },
  {
    "title": "Bat",
    "localUrl": "bat.html",
    "fullUrl": "",
    "description": "A flying mammal known as a bat.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Category",
    "categories": "Animals"
  },
  {
    "title": "Beaver",
    "localUrl": "beaver.html",
    "fullUrl": "",
    "description": "A large rodent known as a beaver.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Cat",
    "localUrl": "cat.html",
    "fullUrl": "",
    "description": "A small domesticated carnivorous mammal.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Elephant",
    "localUrl": "elephant.html",
    "fullUrl": "",
    "description": "A large mammal known for its long trunk.",
    "previewImage": "",
    "keywords": "",
    "language": "eo",
    "namespace": "Category",
    "categories": "Animals"
  },
  {
    "title": "Falcon",
    "localUrl": "falcon.html",
    "fullUrl": "",
    "description": "A bird of prey known for its speed.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Giraffe",
    "localUrl": "giraffe.html",
    "fullUrl": "",
    "description": "The tallest living terrestrial animal.",
    "previewImage": "",
    "keywords": "",
    "language": "de",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Hawk",
    "localUrl": "hawk.html",
    "fullUrl": "",
    "description": "A bird of prey known for its sharp eyesight.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Iguana",
    "localUrl": "iguana.html",
    "fullUrl": "",
    "description": "A large, herbivorous lizard.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Special",
    "categories": "Animals"
  },
  {
    "title": "Jaguar",
    "localUrl": "jaguar.html",
    "fullUrl": "",
    "description": "A large feline found in the Americas.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Template",
    "categories": "Animals"
  },
  {
    "title": "Kangaroo",
    "localUrl": "kangaroo.html",
    "fullUrl": "",
    "description": "A marsupial from Australia.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Category",
    "categories": "Animals"
  },
  {
    "title": "Lion",
    "localUrl": "lion.html",
    "fullUrl": "",
    "description": "A large carnivorous feline known as the king of the jungle.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Monkey",
    "localUrl": "monkey.html",
    "fullUrl": "",
    "description": "A primate known for its intelligence.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Special",
    "categories": "Animals"
  },
  {
    "title": "Narwhal",
    "localUrl": "narwhal.html",
    "fullUrl": "",
    "description": "A medium-sized toothed whale known for its long tusk.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Owl",
    "localUrl": "owl.html",
    "fullUrl": "",
    "description": "A nocturnal bird of prey with a distinctive hoot.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Penguin",
    "localUrl": "penguin.html",
    "fullUrl": "",
    "description": "A flightless bird that lives in the Southern Hemisphere.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Template",
    "categories": "Animals"
  },
  {
    "title": "Quokka",
    "localUrl": "quokka.html",
    "fullUrl": "",
    "description": "A small marsupial known for its smile.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Raccoon",
    "localUrl": "raccoon.html",
    "fullUrl": "",
    "description": "A nocturnal mammal known for its masked face.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Snake",
    "localUrl": "snake.html",
    "fullUrl": "",
    "description": "A legless reptile with a long body.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Tiger",
    "localUrl": "tiger.html",
    "fullUrl": "",
    "description": "A large carnivorous feline with a striped coat.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Urchin",
    "localUrl": "urchin.html",
    "fullUrl": "",
    "description": "A small, spiny sea creature.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Special",
    "categories": "Animals"
  },
  {
    "title": "Vulture",
    "localUrl": "vulture.html",
    "fullUrl": "",
    "description": "A bird of prey known for feeding on carrion.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Walrus",
    "localUrl": "walrus.html",
    "fullUrl": "",
    "description": "A large marine mammal with long tusks.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Xerus",
    "localUrl": "xerus.html",
    "fullUrl": "",
    "description": "A type of ground squirrel found in Africa.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Yak",
    "localUrl": "yak.html",
    "fullUrl": "",
    "description": "A long-haired domesticated bovid found in the Himalayas.",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "Zebra",
    "localUrl": "zebra.html",
    "fullUrl": "",
    "description": "An African wild horse with black-and-white stripes.",
    "previewImage": "",
    "keywords": "",
    "language": "ka",
    "namespace": "Main",
    "categories": "Animals"
  },
  {
    "title": "YouTube video",
    "localUrl": "asdasdasdfasd",
    "fullUrl": "",
    "description": "New video idea",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Video",
    "categories": ""
  },
  {
    "title": "Norma's photo",
    "localUrl": "asdadgaxdSD",
    "fullUrl": "",
    "description": "New photo idea",
    "previewImage": "",
    "keywords": "",
    "language": "en",
    "namespace": "Image",
    "categories": ""
  }
];